Repository TeamCOMPAS/COMPAS, pull requests merged in 2020-12, with the labels that each got.

#489 Fix bug in LBV winds for fLBV=0.0
  src/BaseStar.cpp
  src/changelog.h
Labels: bug

#473 Adding some documentation to Ilya's wonderful fast cosmic integration
  postProcessing/Folders/CosmicIntegration/PythonScripts/ClassCOMPAS.py
  postProcessing/Folders/CosmicIntegration/PythonScripts/FastCosmicIntegration.py
Labels: code cleanup/optimisation

#496 added option to run postprocessing in an alternative directory
  defaults/postProcessing.py
Labels: enhancement
