Repository TeamCOMPAS/COMPAS, pull requests merged in 2020-04, with the labels that each got.

#221 Issue 218 - logfile definitions parser lookup table changed erroneously
  src/constants.h
  src/utils.h
Labels: bug

#240 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#242 Update docs to reflect pre2ndSN -> preSN change
  docs/COMPAS_Doc.docx
  docs/COMPAS_Doc.pdf
Labels: documentation
