Repository TeamCOMPAS/COMPAS, pull requests merged in 2021-05, with the labels that each got.

#550 Issue548 +
  postProcessing/Folders/H5/PythonScripts/h5view.py
  src/BaseBinaryStar.cpp
  src/BaseBinaryStar.h
  src/BinaryStar.cpp
  src/BinaryStar.h
  src/Log.cpp
  src/Log.h
  src/changelog.h
  src/main.cpp
Labels: severity_moderate, urgency_low

#566 Change default LBV wind prescription 💨
  defaults/pythonSubmit.py
  docs/COMPAS_Doc.pdf
  docs/COMPAS_LaTex/sections/Appendices/ProgramOptions.tex
  docs/COMPAS_LaTex/sections/RevisionHistory.tex
  src/BaseStar.cpp
  src/Options.cpp
  src/changelog.h
Labels: enhancement

#561 Update cosmic post processing notebooks
  postProcessing/Folders/CosmicIntegration/0_CosmicIntegrationOverview.ipynb
  postProcessing/Folders/CosmicIntegration/1_ClassCOMPAS.ipynb
  postProcessing/Folders/CosmicIntegration/2_MSSFR-or-SFRD-prescriptions.ipynb
  postProcessing/Folders/CosmicIntegration/2_MSSFR.ipynb
  postProcessing/Folders/CosmicIntegration/GSMFplot.png
  postProcessing/Folders/CosmicIntegration/MZrelations.png
  postProcessing/Folders/CosmicIntegration/SFRplot.png
Labels: enhancement

#567 Add methods paper plots/code (Figures 5-7)
  examples/methods_paper_plots/fig_5_HR_diagram/README.md
  examples/methods_paper_plots/fig_5_HR_diagram/create_fig_5_grid.py
  examples/methods_paper_plots/fig_5_HR_diagram/hrd.pdf
  examples/methods_paper_plots/fig_5_HR_diagram/make_fig_5.ipynb
  examples/methods_paper_plots/fig_5_HR_diagram/pythonSubmit.py
  examples/methods_paper_plots/fig_6_max_R/README.md
  examples/methods_paper_plots/fig_6_max_R/create_fig_6_grid.py
  examples/methods_paper_plots/fig_6_max_R/make_fig_6.ipynb
  examples/methods_paper_plots/fig_6_max_R/maximum_radius.pdf
  examples/methods_paper_plots/fig_6_max_R/pythonSubmit.py
  examples/methods_paper_plots/fig_7_MS_lifetime/README.md
  examples/methods_paper_plots/fig_7_MS_lifetime/main_sequence_lifetime.pdf
  examples/methods_paper_plots/fig_7_MS_lifetime/make_fig_7.ipynb
  examples/methods_paper_plots/stellar_types.py
Labels: documentation
