Repository TeamCOMPAS/COMPAS, pull requests merged in 2024-10, with the labels that each got.

#1232 Add tidal timestep limit, minor tides enhancements
  online-docs/pages/User guide/Program options/program-options-list-defaults.rst
  src/BaseBinaryStar.cpp
  src/BaseStar.cpp
  src/changelog.h
  src/constants.h
Labels: enhancement, urgency_moderate

#1235 Changed order of binary and stellar evolution in BaseBinaryStar::Evolve()
  online-docs/pages/User guide/COMPAS output/standard-logfiles-record-types-bse-detailed-output.rst
  src/BaseBinaryStar.cpp
  src/BinaryConstituentStar.cpp
  src/LogTypedefs.h
  src/changelog.h
Labels: enhancement, severity_moderate, urgency_moderate

#1251 Fix for Issue 1246 and others
  online-docs/pages/User guide/Program options/program-options-list-defaults.rst
  online-docs/pages/whats-new.rst
  src/BaseBinaryStar.cpp
  src/BaseStar.cpp
  src/Options.cpp
  src/Options.h
  src/changelog.h
  src/main.cpp
  src/utils.cpp
Labels: bug, severity_moderate, urgency_moderate

#1268 Fix for error parsing deprecated option properties in logfile-definitions file
  online-docs/pages/User guide/Program options/program-options-list-defaults.rst
  src/Log.cpp
  src/LogTypedefs.h
  src/Options.cpp
  src/Options.h
  src/changelog.h
  src/main.cpp
Labels: bug, severity_moderate, urgency_high
