Repository TeamCOMPAS/COMPAS, pull requests merged in 2024-04, with the labels that each got.

#1092 Defect repair - Fix for issue #1074 - SSE Supernova records duplicated
  src/BaseStar.cpp
  src/BaseStar.h
  src/GiantBranch.cpp
  src/Log.h
  src/Star.cpp
  src/WhiteDwarfs.cpp
  src/changelog.h
Labels: bug, severity_moderate, urgency_moderate

#1090 Defect Repair: Issue 1084
  src/BH.h
  src/BaseBinaryStar.cpp
  src/BaseBinaryStar.h
  src/BaseStar.cpp
  src/BaseStar.h
  src/BinaryConstituentStar.h
  src/BinaryStar.cpp
  src/BinaryStar.h
  src/CH.h
  src/CHeB.h
  src/COWD.h
  src/EAGB.h
  src/FGB.h
  src/GiantBranch.cpp
  src/GiantBranch.h
  src/HG.cpp
  src/HG.h
  src/HeGB.h
  src/HeHG.h
  src/HeMS.h
  src/HeWD.h
  src/Log.h
  src/MR.h
  src/MS_gt_07.h
  src/MS_lte_07.h
  src/MainSequence.cpp
  src/MainSequence.h
  src/NS.h
  src/ONeWD.h
  src/Remnants.h
  src/Star.cpp
  src/Star.h
  src/TPAGB.h
  src/WhiteDwarfs.h
  src/changelog.h
  src/constants.h
  src/main.cpp
  src/profiling.h
  src/utils.h
  src/vector3d.cpp
  src/vector3d.h
Labels: bug, severity_minor, urgency_moderate

#1100 Don't allow ephemeral clones to operate the SSE SN stash
  src/BaseStar.cpp
  src/GiantBranch.cpp
  src/GiantBranch.h
  src/Star.cpp
  src/changelog.h
Labels: bug, severity_minor, urgency_low

#1083 Realistic Tides
  compas_python_utils/preprocessing/compasConfigDefault.yaml
  online-docs/pages/User guide/Program options/program-options-list-defaults.rst
  online-docs/pages/whats-new.rst
  src/BaseBinaryStar.cpp
  src/BaseBinaryStar.h
  src/BaseStar.cpp
  src/BaseStar.h
  src/GiantBranch.cpp
  src/GiantBranch.h
  src/HG.h
  src/MainSequence.cpp
  src/Options.cpp
  src/Options.h
  src/Remnants.h
  src/Star.h
  src/changelog.h
  src/compasConfigDefault.yaml
  src/constants.h
  src/yaml.h
Labels: enhancement
