Repository TeamCOMPAS/COMPAS, pull requests merged in 2024-11, with the labels that each got.

#1275 Fix for issues 1263 1272 1273
  online-docs/pages/User guide/Program options/program-options-list-defaults.rst
  src/Options.cpp
  src/changelog.h
  src/yaml.h
Labels: bug, documentation, severity_moderate, urgency_moderate

#1283 Spin retention after envelope loss
  src/BaseBinaryStar.cpp
  src/Star.cpp
  src/changelog.h
Labels: bug, severity_minor, urgency_moderate

#1296 Added functionality to allow stellar mergers (for BSE) to be logged to switchlog file
  online-docs/pages/User guide/COMPAS output/standard-logfiles-default-record-specifications-BSE-switchlog.rst
  online-docs/pages/whats-new.rst
  src/BaseBinaryStar.cpp
  src/BaseBinaryStar.h
  src/BaseStar.cpp
  src/Log.cpp
  src/Log.h
  src/changelog.h
Labels: enhancement, severity_minor, urgency_low
