Repository TeamCOMPAS/COMPAS, pull requests merged in 2024-09, with the labels that each got.

#1221 Fix for issue 1219: Option --black-hole-kicks-mode (aka --black-hole-kicks) ignored
  online-docs/pages/whats-new.rst
  src/BH.cpp
  src/BH.h
  src/BaseStar.cpp
  src/changelog.h
Labels: bug, severity_major, urgency_high

#1223 Fixed application of WolfRayetFactor
  src/BaseStar.cpp
  src/HeMS.cpp
  src/changelog.h
Labels: bug, severity_minor

#1216 Improved treatment of chemically homogeneously evolving stars
  compas_python_utils/preprocessing/compasConfigDefault.yaml
  online-docs/pages/User guide/COMPAS output/standard-logfiles-record-specification-options.rst
  online-docs/pages/User guide/COMPAS output/standard-logfiles-record-specification-stellar.rst
  online-docs/pages/User guide/Program options/program-options-list-defaults.rst
  online-docs/pages/whats-new.rst
  src/BaseBinaryStar.cpp
  src/BaseStar.cpp
  src/BaseStar.h
  src/CH.cpp
  src/CH.h
  src/CHeB.cpp
  src/CHeB.h
  src/COWD.h
  src/HG.h
  src/HeMS.cpp
  src/HeMS.h
  src/HeWD.h
  src/LogTypedefs.h
  src/MainSequence.cpp
  src/MainSequence.h
  src/ONeWD.h
  src/Options.cpp
  src/Options.h
  src/Remnants.h
  src/Star.h
  src/WhiteDwarfs.h
  src/changelog.h
  src/utils.cpp
  src/utils.h
  src/yaml.h
Labels: enhancement
