Repository TeamCOMPAS/COMPAS, pull requests merged in 2025-01, with the labels that each got.

#1319 Fix for Issue 1317
  src/BaseBinaryStar.cpp
  src/changelog.h
Labels: bug, severity_moderate, urgency_low

#1320 Fix for issue 1317
  src/BaseBinaryStar.cpp
  src/changelog.h
Labels: bug, severity_moderate, urgency_low

#1318 Tides Eccentricity Behavior Fix
  src/BaseBinaryStar.cpp
  src/changelog.h
Labels: enhancement, severity_moderate, urgency_moderate

#1321 CHE Logic Fix for Issue #1303
  src/BaseBinaryStar.cpp
  src/changelog.h
Labels: bug, enhancement, severity_moderate, urgency_moderate

#1292 Implementing the Shikauchi+ (2024) core mass prescription for main sequence stars
  compas_python_utils/preprocessing/compasConfigDefault.yaml
  online-docs/pages/User guide/Program options/program-options-list-defaults.rst
  online-docs/pages/whats-new.rst
  src/BaseBinaryStar.cpp
  src/BaseStar.cpp
  src/BaseStar.h
  src/CH.h
  src/GiantBranch.h
  src/HG.cpp
  src/HG.h
  src/MS_gt_07.h
  src/MainSequence.cpp
  src/MainSequence.h
  src/Options.cpp
  src/Options.h
  src/Star.h
  src/changelog.h
  src/constants.h
  src/typedefs.h
  src/yaml.h
Labels: enhancement

#1322 (partial?) fix for issue 1149
  online-docs/pages/whats-new.rst
  src/TPAGB.cpp
  src/changelog.h
Labels: bug, severity_moderate, urgency_high

#1326 Fixes initialisation in MS_gt_07::Initialise() for CORE_MASS_PRESCRIPTION::SHIKAUCHI
  src/BaseBinaryStar.cpp
  src/MS_gt_07.h
  src/changelog.h
Labels: bug, severity_minor, urgency_low
