Repository TeamCOMPAS/COMPAS, pull requests merged in 2025-04, with the labels that each got.

#1369 Fix for #1365
  src/BaseStar.cpp
  src/changelog.h
Labels: bug, severity_minor, urgency_moderate

#1370 Minor fixes
  src/BaseStar.cpp
  src/MainSequence.h
  src/changelog.h
Labels: bug, documentation, severity_minor, urgency_low

#1371 Add option "--timestep-multipliers" to enable more granular, phase-dependent, timestep multipliers
  online-docs/pages/User guide/Program options/program-options-list-defaults.rst
  online-docs/pages/User guide/Program options/program-options-vector-options.rst
  online-docs/pages/User guide/Running COMPAS/running-grid.rst
  online-docs/pages/User guide/docker.rst
  online-docs/pages/whats-new.rst
  src/BaseBinaryStar.cpp
  src/BaseBinaryStar.h
  src/HG.cpp
  src/Log.cpp
  src/Log.h
  src/LogTypedefs.h
  src/Options.cpp
  src/Options.h
  src/Star.cpp
  src/changelog.h
  src/constants.h
  src/main.cpp
  src/typedefs.h
Labels: enhancement, severity_minor, urgency_low

#1372 Add option "--timestep-multipliers" to enable more granular, phase-dependent, timestep multipliers
  compas_python_utils/preprocessing/compasConfigDefault.yaml
  online-docs/pages/User guide/Program options/program-options-list-defaults.rst
  online-docs/pages/User guide/Program options/program-options-vector-options.rst
  online-docs/pages/User guide/Running COMPAS/running-grid.rst
  online-docs/pages/User guide/docker.rst
  online-docs/pages/whats-new.rst
  src/BaseBinaryStar.cpp
  src/BaseBinaryStar.h
  src/HG.cpp
  src/Log.cpp
  src/Log.h
  src/LogTypedefs.h
  src/Options.cpp
  src/Options.h
  src/Star.cpp
  src/changelog.h
  src/constants.h
  src/main.cpp
  src/typedefs.h
  src/yaml.h
Labels: enhancement, severity_minor, urgency_low
